version: '3'
services:
  bot:
    container_name: phoenix-bot
    image: ghcr.io/sofia-q/phoenix-bot:latest
    restart: always
    env_file:
      - .env
    volumes:
      - .:/discord-bot
    command: ['./main']
  db:
    image: mysql:latest
    container_name: mysql_db
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PW}
      MYSQL_DATABASE: phoenix_bot_db
      MYSQL_ROOT_PASSWORD: rootpw1234
    expose:
      # Opens port 3306 on the container
      - '3306'
    volumes:
      - phoenix_bot_db:/var/lib/mysql
volumes:
  phoenix_bot_db: